### ISSUE TITLE
version number is incorrect

### ISSUE THREAD

**Issue by shantanugadgil** [seatgeek/nomad-helper#3]
Hi,

I think the following needs to change:
https://github.com/seatgeek/nomad-helper/blob/3aa6fad460d7b32afa52b792b3b3a6604c57a72f/main.go#L23

# Steps
```
wget https://github.com/seatgeek/nomad-helper/releases/download/v2.0.0/nomad-helper-linux-amd64
chmod +x nomad-helper-linux-amd64
./nomad-helper-linux-amd64 -v
nomad-helper version 1.0
```

Cheers and Regards,
Shantanu

Awesome tool "nomad-helper" 👍 👍

**Comment by jippi** [comment]
yeah, i'm not actually using that value, i should probably just remove it, or figure out how to encode it in the binary :)

**Comment by josegonzalez** [comment]
@jippi I do something like this for the seamstress cli client in the Makefile during releases:

```
	@TMPFILE=$(mktemp "/tmp/$(basename $0).XXXXXX") \
		&& current_version=$$(cat client/main.go | grep "var version" | cut -d ' ' -f 4 | tr -d '"') \
		&& next_version=$$((current_version + 1)) \
		&& echo "\033[0;33m   >\033[0m \033[0;35m$${current_version}\033[0m -> \033[0;35m$${next_version}\033[0m\n" \
		&& sed "s/var version = \"$$current_version\"/var version = \"$$next_version\"/" client/main.go > $TMPFILE && mv $TMPFILE client/main.go \
		&& echo "\033[0;33m--->\033[0m Adding changed files to git" \
		&& git add client/main.go
```

**Comment by jippi** [comment]
@josegonzalez the "right" / "native" way to do it is [like in hashi-ui](https://github.com/jippi/hashi-ui/blob/master/backend/Makefile#L99) using `ldflags`

```
GIT_COMMIT := $(shell git describe --tags)
GIT_DIRTY := $(if $(shell git status --porcelain),+CHANGES)
GO_LDFLAGS := "-X main.GitCommit=$(GIT_COMMIT)$(GIT_DIRTY)"

go build -o $@ -ldflags $(GO_LDFLAGS)
```

and then have

```
var (
	GitCommit string // Filled in by the compiler
)
```

in package `main` in my go code

**Comment by josegonzalez** [comment]
Oh wow I didn't know that.

**Comment by shantanugadgil** [comment]
as of version 3.0.0, this has been fixed. closing.
