### ISSUE TITLE
how to specify the SSH key while connecting

### ISSUE THREAD

**Issue by shantanugadgil** [seatgeek/nomad-helper#5]
This is issue is related to `nomad-helper attach`.

On an AWS setup, I have a shared server where sets of machines which have different SSH keys.
Would it be possible to allow the user to specify the **ssh key**?

I cannot expect the ~/.ssh/config to be setup as these machines are part of  AWS AutoScaling Groups

For now, I am making do with multiple `IdentityFile` lines with a IP list narrowed down based on subnet ranges. 🙄 😩 

Regards,
Shantanu

**Comment by ketzacoatl** [comment]
Would it be possible to add a cli param to the `nomad-helper attach` command for this? Eg, we could tell `attach` what it should use as a path to the `ssh_config`?

In my case, each deployment has its own `ssh_config`, so when I run a tool that uses SSH, I provide `-F`, and a cli param would make `nomad-helper attach` available in these deployments.

**Comment by shantanugadgil** [comment]
I hadn't thought of this, being able to specify an ssh_config is a much better/cleaner approach! 👍👍👍

**Comment by shantanugadgil** [comment]
bump @jippi

**Comment by jippi** [comment]
Personally I depend on `~/.ssh/config` for all SSH configuration like keys and so forth

**Comment by shantanugadgil** [comment]
would something like `NOMAD_HELPER_SSH_COMMAND` make sense then? (equivalent of `GIT_SSH_COMMAND`)

**Comment by jippi** [comment]
Yes, I'm fine with such a change I think :)
