### ISSUE TITLE
[feature request] linux arm64 builds

### ISSUE THREAD

**Issue by shantanugadgil** [seatgeek/nomad-helper#82]
Any chance of getting linux arm64 builds? :smile:

**Comment by josegonzalez** [comment]
I think we'd be open to an MR for it. Might just be modifying this: https://github.com/seatgeek/nomad-helper/blob/master/.github/workflows/build.yml#L21

**Comment by shantanugadgil** [comment]
added this: https://github.com/seatgeek/nomad-helper/pull/83

Not sure if it will suffice though :thinking:

**Comment by shantanugadgil** [comment]
#87

**Comment by josegonzalez** [comment]
This is done :)
